### ISSUE TITLE
勇者から感謝されたい

### ISSUE THREAD

**Issue by EngineerLabShimazu** [GenkiShimazu/oracle-follower#1]
### Story

```
user: アレクサ、お告げの勇者を開いて


勇者(from alexa):
こんにちは神様。本日も{○○してくださって}、ありがとうございます。

SKILL END
```

### AC

- 勇者が感謝の意を述べる
- {○○してくださって} はランダムのテキストを述べる
- ランダムテキストは、１日１回変わる

### {○○してくださって}

- 見守ってくださって、
- お気にかけてくださって
- 健やかに暮らさせていただき
- 祈りを受け入れてくださり

**Comment by emuyuu** [comment]
今こうなってるんですが、初回の挨拶はどうします？？
```
speech_text = "はじめまして神様！あなたの勇者をご紹介します。" \
                      "初めまして神様！本日からあなたへの忠誠を誓います。それでは、また明日。"
```

**Comment by EngineerLabShimazu** [comment]
初回起動と、それ以降で分けたいです！
が一旦消してOKです！(このPBIでは、「初回起動」の概念は入れなくてOKです。)

**Comment by EngineerLabShimazu** [comment]
2pointくらい
