### ISSUE TITLE
勇者にお告げを伝えたい (7)

### ISSUE THREAD

**Issue by EngineerLabShimazu** [GenkiShimazu/oracle-follower#2]
7point

### Story

```
user: アレクサ、お告げの勇者を開いて

勇者:
user: 
アレクサ、お告げの勇者を開いて

勇者:
こんにちは神様。
本日も{○○してくださって}、ありがとうございます。

if 起動１回目/日:
ご報告がございます。
昨日は{村A}へ行ったのですが、是非、神様を信仰させていただきたいと申す者共がおります。私の方で、新たな信者として迎え入れさせていただきました。数は N 人でございます。現在の合計はNN人です。
❌else:
❌勇者「現在は{村A}へ向かっています、総信者数はNN人です。あとHH:mm:ss時間後に、完了します。」

if お告げを授かる / 日:
+ お告げを頂戴したく存じます。
+ - 本日は、村A, 村Bのどちらへ向かえばよろしいでしょうか？(closed question)
+ - どちらへ向かえばよろしいでしょうか？(layerd open question)

+ user: {村A: VillageSlot}に{行く: DestinationIntent}と良いよ。

+ 勇者:
+ {村A}へ行くのですね！。ありがとうございます！

SKILL END
```

### AC

- 勇者がお告げを聞いてくること。
- お告げのIntentを、勇者が理解できること。
- お告げのSlotを、勇者が理解できること。
- お告げを聞いた勇者が感謝を述べること。

#### 新しいアーキテクチャを使用した現場復帰

- [x] fof_state_changerをrepository に追加
- [x] SFsのStateのIn, Outをつなぐ(ResultPath)
- [x] lambda_layer(fof_sdk) の has_todays_oracle の関数idが帰ってきちゃうのを修正
- [x] lambda_layerのdeployのshell scriptを追加

#### このPBIの機能

- [x] Destination Intentを追加
- [x] 勇者がお告げを聞いてくるか確認 (fof_state_launch)
- [x] slot.village の中身を、fof_sdk/assets/villages.pyに合わせる ("村あ"とかを正)
- [x] set_should_end_sessionをbackgroudから返すようにする
- [x] DestinationIntentHandler(fof_alexa_front.py) の処理を記載
- [x] 日付が変わったらdestinationを削除する

**Comment by EngineerLabShimazu** [comment]
{行く}
表記揺れはどっちでもいいです。

**Comment by EngineerLabShimazu** [comment]
今までの、信者が増える機能とかってどうしますか？
こちらもSKILL 終了してますが🥺

**Comment by EngineerLabShimazu** [comment]
1. 信者が増える
2. お告げを聞いてくる

の順番でレスポンスして欲しいです。
User Story変えときます！🙇‍♀️

**Comment by EngineerLabShimazu** [comment]
front-back
input: {'alexa_user_id': dummy_id, 'intent': launch, 'destination': '村A'}
output: {'response_text': hero_message}


intent: launch, destination

**Comment by EngineerLabShimazu** [comment]
backend-db
input: {destination: '村A'}

**Comment by EngineerLabShimazu** [comment]
```
score = handler_input.request_envelope.request.intent.slots['village'].value
```

**Comment by emuyuu** [comment]
次にやることはdestinationを認識して保存することなので、私一人では無理でした🐙
右耳で島津さんの話を聞きながら、アレクサ開発やインテントについて調べます🐠
